### PR TITLE
Add the port 80 uart to the rome

### PR DESCRIPTION
**Pull request by rminnich**
The port 80 uart is very useful when the serial is dead for some reason.

### CODE REVIEW

**Comment by rminnich** [comment]
I realize this is not The Best Code Ever but I hope the intent is clear. 

This is actually something we are using NOW to debug a problem.

**Review by Rwantare — COMMENTED** [review]
Should DIT be tracked on master? It only works on your machine

**Comment by rminnich** [comment]
removed DIT

**Review by Rwantare — APPROVED** [review]
Looks good to me

**Review by rjoleary — APPROVED** [review]

**Comment by rminnich** [comment]
it was pretty cool to see the console output on the bmc port 80 display ...

**Pull request merged**
