### PR TITLE
Remove non-necessary Makefile.toml

### PR DESCRIPTION
**Pull request by gevorgyana**
Most probably, the author
of 12c6b52cb42e10c forgot to do it.

As stated in that commit, the goal was to remove usages of cargo-make.

Signed-off-by: Artyom Gevorgyan <artemhevorhian@gmail.com>

### CODE REVIEW

**Review by orangecms — DISMISSED** [review]
looks like a leftover, yup :)

**Comment by fotonick** [comment]
If it's convenient, would you remove `src/mainboard/opentitan/crb/Makefile.toml`, as well? Looks like the same deal.

**Comment by doriath** [comment]
nit: what do you think about folding both commits into one?

**Comment by gevorgyana** [comment]
@doriath I thought we do squashed merges into master, okay.

**Review by orangecms — APPROVED** [review]

**Comment by doriath** [comment]
I believe we do `rebase` by default (in `.github/auto-merge.yml` there is `mergeMethod: rebase`.

**Comment by orangecms** [comment]
Correct. When there is a pile of patches and auto-merge kicks in, they would end up just like that in master. Also, if someone were to merge a set of patches, then they would need to write a new message when squashing, so yea... Just prepare the patches so that they can be taken as-is, that makes it easy to handl them. :)

**Comment by gevorgyana** [comment]
@doriath @orangecms Thanks for information :+1:

**Pull request merged**
