### PR TITLE
Bring back mainboard/emulation/qemu-riscv

### PR DESCRIPTION
**Pull request by rminnich**
This builds, as it has been drastically stripped down.

The sunxi nezha target should indicate how to add back drivers and such.

Signed-off-by: Ronald G. Minnich <rminnich@google.com>

### CODE REVIEW

**Comment by bwerthmann** [comment]
Does this fix #568 ?

**Comment by rminnich** [comment]
I'm still trying to figure out how to crate the bios image

**Comment by luojia65** [comment]
@rminnich We can modify xtask builder to build an image. We may either add a hard coded platform in that package, or add a generic platform configuration parser for it.

**Comment by rminnich** [comment]
is there any reason NOT to bring layoutflash back to life? It worked pretty well for building ROM images from a dtb and did not require specialization in xtask

**Review by orangecms — APPROVED** [review]

**Comment by orangecms** [comment]
> is there any reason NOT to bring layoutflash back to life? It worked pretty well for building ROM images from a dtb and did not require specialization in xtask

I am very much in favor of using layoutflash _in xtask_. We can make the image stitching very declarative through it.

**Pull request merged**
