### PR TITLE
Organize oreboot project into cargo workspace

### PR DESCRIPTION
**Pull request by luojia65**
This pull request is a successor to https://github.com/oreboot/oreboot/pull/553, it organizes the Oreboot project into one cargo workspace.

After this pull request, you may:

- run `cargo fmt` to reformat, `cargo clippy` to clippy check all packages under oreboot
- run `cargo clean` to clean the build cache shared by all oreboot packages
- discover a significant compile speed boost if you build all boards

The build framework is still based on existing Makefile system, but this reorganization would allow us to write a xtask based build framework in the future, onto project that is arranged under a cargo workspace.

## Checklist

- [x] A proper commit message

## Details to this change

Previously, oreboot consists of individual cargo packages. This would comply with C code, but it can't share incremental build caches. In this commit we will organize it into one workspace for cargo, in this case cargo would use the same target path so compilation caches would be shared.

To orgainze workspace, we rearranged soc and cpu modules, as is done in driver module. This rearrangement does not include any change to working code except only for changes to dependency path.

This commit includes changes to build.rs file, it's mostly used in FSP build and link script discovery. Changes to them will allow to detect the 3rdparty directory and search for link.ld in every path of organized workspace, so we may build them wherever we are at in the project directory.

In Cargo `[profile.release]` is defined in workspace configuration, I remove them from each individual project or Cargo would warn us that this profile configuration is ignored as already been configurated by workspace.

The commit also includes multiple clippy fixes. The project after this commit would still need makefiles to help building, but this organization to workspace would furtherly allow us to develop a xtask based building framework onto oreboot project.

### CODE REVIEW

**Comment by luojia65** [comment]
Work in progress: blob size regression

**Comment by rminnich** [comment]
This is dramatically better. I can not repro the build failure at home -- what do you think is going on?

I like this change.

**Review by rminnich — CHANGES_REQUESTED** [review]
we can't have all mainboards using the same target directory. I think this may not work.

Even similar architectures may have different build constraints. We need to talk about this a bit.

**Comment by rminnich** [comment]
OH WAIT.
There's a little problem here. The target directory for every mainboard of a given architecture is the same. 
TARGET_DIR   = /home/runner/work/oreboot/oreboot/target/aarch64-unknown-none-softfloat/release
TARGET_DIR=/home/runner/work/oreboot/oreboot/target/aarch64-unknown-none-softfloat/release cargo run --target x86_64-unknown-linux-gnu --manifest-path /home/runner/work/oreboot/oreboot/tools/layoutflash/Cargo.toml -- /home/runner/work/oreboot/oreboot/target/aarch64-unknown-none-softfloat/release/fixed-dtfs.dtb /home/runner/work/oreboot/oreboot/target/aarch64-unknown-none-softfloat/release/image.bin
TARGET_DIR   = /home/runner/work/oreboot/oreboot/target/arm-none-eabihf/release
TARGET_DIR=/home/runner/work/oreboot/oreboot/target/arm-none-eabihf/release cargo run --target x86_64-unknown-linux-gnu --manifest-path /home/runner/work/oreboot/oreboot/tools/layoutflash/Cargo.toml -- /home/runner/work/oreboot/oreboot/target/arm-none-eabihf/release/fixed-dtfs.dtb /home/runner/work/oreboot/oreboot/target/arm-none-eabihf/release/image.bin
TARGET_DIR   = /home/runner/work/oreboot/oreboot/target/armv7a-none-eabihf/release
TARGET_DIR=/home/runner/work/oreboot/oreboot/target/armv7a-none-eabihf/release cargo run --target x86_64-unknown-linux-gnu --manifest-path /home/runner/work/oreboot/oreboot/tools/layoutflash/Cargo.toml -- /home/runner/work/oreboot/oreboot/target/armv7a-none-eabihf/release/fixed-dtfs.dtb /home/runner/work/oreboot/oreboot/target/armv7a-none-eabihf/release/image.bin
TARGET_DIR   = /home/runner/work/oreboot/oreboot/target/armv7r-none-eabi/release
TARGET_DIR=/home/runner/work/oreboot/oreboot/target/armv7r-none-eabi/release cargo run --target x86_64-unknown-linux-gnu --manifest-path /home/runner/work/oreboot/oreboot/tools/layoutflash/Cargo.toml -- /home/runner/work/oreboot/oreboot/target/armv7r-none-eabi/release/fixed-dtfs.dtb /home/runner/work/oreboot/oreboot/target/armv7r-none-eabi/release/image.bin
TARGET_DIR   = /home/runner/work/oreboot/oreboot/target/riscv32imc-unknown-none-elf/release
TARGET_DIR   = /home/runner/work/oreboot/oreboot/target/riscv64gc-unknown-none-elf/release
TARGET_DIR=/home/runner/work/oreboot/oreboot/target/riscv64gc-unknown-none-elf/release cargo run --target x86_64-unknown-linux-gnu --manifest-path /home/runner/work/oreboot/oreboot/tools/layoutflash/Cargo.toml -- /home/runner/work/oreboot/oreboot/target/riscv64gc-unknown-none-elf/release/fixed-dtfs.dtb /home/runner/work/oreboot/oreboot/target/riscv64gc-unknown-none-elf/release/image.bin
TARGET_DIR   = /home/runner/work/oreboot/oreboot/target/riscv64imac-unknown-none-elf/release
TARGET_DIR=/home/runner/work/oreboot/oreboot/target/riscv64imac-unknown-none-elf/release cargo run --target x86_64-unknown-linux-gnu --manifest-path /home/runner/work/oreboot/oreboot/tools/layoutflash/Cargo.toml -- /home/runner/work/oreboot/oreboot/target/riscv64imac-unknown-none-elf/release/fixed-dtfs.dtb /home/runner/work/oreboot/oreboot/target/riscv64imac-unknown-none-elf/release/image.bin
TARGET_DIR   = /home/runner/work/oreboot/oreboot/target/x86_64-unknown-none-oreboot/release
TARGET_DIR=/home/runner/work/oreboot/oreboot/target/x86_64-unknown-none-oreboot/release cargo run --target x86_64-unknown-linux-gnu --manifest-path /home/runner/work/oreboot/oreboot/tools/layoutflash/Cargo.toml -- /home/runner/work/oreboot/oreboot/target/x86_64-unknown-none-oreboot/release/fixed-dtfs.dtb /home/runner/work/oreboot/oreboot/target/x86_64-unknown-none-oreboot/release/image.bin
TARGET_DIR   = /home/runner/work/oreboot/oreboot/target/x86_64-unknown-none/release
TARGET_DIR=/home/runner/work/oreboot/oreboot/target/x86_64-unknown-none/release cargo run --target x86_64-unknown-linux-gnu --manifest-path /home/runner/work/oreboot/oreboot/tools/layoutflash/Cargo.toml -- /home/runner/work/oreboot/oreboot/target/x86_64-unknown-none/release/fixed-dtfs.dtb /home/runner/work/oreboot/oreboot/target/x86_64-unknown-none/release/image.bin

which means when I build them all, they step on top of each other. Definitely not what we want. Further, there may be different build constraints for different mainboards of the same architecture.Not all x86 can end up with the same definitions.

**Comment by rminnich** [comment]
what we have today
./tools/layoutflash/target
./src/mainboard/asrock/a300m-stx/target
./src/mainboard/nuvoton/npcm7xx/target
./src/mainboard/google/trembyle/target
./src/mainboard/aaeon/upxtreme/target
./src/mainboard/ast/ast25x0/target
./src/mainboard/sunxi/nezha/target
./src/mainboard/sifive/hifive/target
./src/mainboard/amd/romecrb/target
./src/mainboard/emulation/qemu-aarch64/target
./src/mainboard/emulation/qemu-fsp/target
./src/mainboard/emulation/qemu-armv7/target
./src/mainboard/emulation/qemu-q35/target
./src/mainboard/emulation/qemu-riscv/target
./src/mainboard/emulation/qemu-fsp32/target

whereas with this change
rminnich@a300:~/oreboot$ find . -type d -name target -print
./target

this is not what we want.

**Comment by luojia65** [comment]
Thanks for pointing out! I'll change image output file name for each mainboard in a proper way, then I'll re-request for review.

**Comment by luojia65** [comment]
Hello! I fixed overlap issue that existed before in this pull request. I did this by modifying mainboard makefile and fixed-dtfs.dts files, no other code modified comparing with previous force push. I'm re-requesting for review now :)

**Comment by rminnich** [comment]
This still seems not quite right. 

./target/x86_64-unknown-none-oreboot/release/qemu-q35.d
./target/x86_64-unknown-none-oreboot/release/build/qemu-q35-6e33e499ac3d1541
./target/x86_64-unknown-none-oreboot/release/emulation-qemu-q35-fixed-dtfs.dtb
./target/x86_64-unknown-none-oreboot/release/deps/qemu_q35-ec7b665db4536c9a.d
./target/x86_64-unknown-none-oreboot/release/deps/qemu_q35-ec7b665db4536c9a
./target/x86_64-unknown-none-oreboot/release/emulation-qemu-q35-bootblob.bin
./target/x86_64-unknown-none-oreboot/release/qemu-q35
./target/x86_64-unknown-none-oreboot/release/emulation-qemu-q35.bin


Plus, the naming is a bit confusing: in some places we have emulation-qemu-q35 and in others just qemu_q35. 

If we have two mainboards from two vendors named qemu-q35, they are going to collide.

**Comment by luojia65** [comment]
@rminnich: the qemu_q35 in target/.../release/build path is named by cargo program, this name depends on cargo package name, or the name field in Cargo.toml in qemu-q35 package. If it would cause collision, cargo workspace won't allow us to build this package.
If we want to solve this problem, we should rename all mainboard package names in their cargo.toml files. I suggest we do this in the next pull requst, it's already too much change in this PR.

**Comment by luojia65** [comment]
There is a guide on cargo's build caches: https://doc.rust-lang.org/cargo/guide/build-cache.html

**Review by rminnich — APPROVED** [review]
OK, let's go.

**Review by rminnich — APPROVED** [review]

**Pull request merged**
