### PR TITLE
asrock/a300m-stx: initial Rust build setup

### PR DESCRIPTION
**Pull request by orangecms**
This is a 1:1 copy from romecrb, except that src/main.rs is stripped to
only output on the debug port and start.S initializes the super I/O.
The patch.go is documented and adjusted to patch the original ROM image.

Signed-off-by: Daniel Maslowski <info@orangecms.org>

### CODE REVIEW

**Comment by orangecms** [comment]
something is still a bit messed up; I'm checking -.-

**Comment by orangecms** [comment]
I missed the `.cargo/` directory, now it works :)

**Comment by orangecms** [comment]
I recall some sort of list of WIP boards or something. I guess I need to add this one to the list to pass... right?

**Review by daym — APPROVED** [review]
Looks good!

**Review by rminnich — APPROVED** [review]

**Pull request merged**
