### PR TITLE
Nightly 2022 01 11

### PR DESCRIPTION
**Pull request by orangecms**
doesn't work just yet, needs more work somewhat around linking?

with `.cargo/config.toml`
```
[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
  "-C", "relocation-model=pic",
  "-C", "link-arg=-Tlink.ld",
  "-C", "link-arg=-nostdlib",
  "-Z", "emit-stack-sizes",
]
```
this happens:
```
error: linking with `rust-lld` failed: exit status: 1
  |
  = note: "rust-lld" "-flavor" "gnu" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/upxtreme-c2a0d6446acbf0ac.upxtreme.f7483b69-cgu.8.rcgu.o" "--as-needed" "-L" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps" "-L" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/release/deps" "-L" "/home/dama/.rustup/toolchains/nightly-2022-02-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-none/lib" "-Bstatic" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/libcompiler_builtins-5c6144d7d8f77801.rlib" "-Bdynamic" "--eh-frame-hdr" "-znoexecstack" "-L" "/home/dama/.rustup/toolchains/nightly-2022-02-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-none/lib" "-o" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/upxtreme-c2a0d6446acbf0ac" "--gc-sections" "-pie" "-zrelro" "-znow" "-Tlink.ld" "-nostdlib"
  = note: rust-lld: error: no memory region specified for section '.dynsym'
          rust-lld: error: no memory region specified for section '.gnu.hash'
          rust-lld: error: no memory region specified for section '.hash'
          rust-lld: error: no memory region specified for section '.dynstr'
          rust-lld: error: no memory region specified for section '.rela.dyn'
          rust-lld: error: no memory region specified for section '.dynamic'
          rust-lld: error: no memory region specified for section '.got'
```

without the config (current code in `main`):

```
error: linking with `rust-lld` failed: exit status: 1
  |
  = note: "rust-lld" "-flavor" "gnu" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/upxtreme-c2a0d6446acbf0ac.upxtreme.f7483b69-cgu.8.rcgu.o" "--as-needed" "-L" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps" "-L" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/release/deps" "-L" "/home/dama/.rustup/toolchains/nightly-2022-02-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-none/lib" "-Bstatic" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/libcompiler_builtins-5c6144d7d8f77801.rlib" "-Bdynamic" "--eh-frame-hdr" "-znoexecstack" "-L" "/home/dama/.rustup/toolchains/nightly-2022-02-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-none/lib" "-o" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/upxtreme-c2a0d6446acbf0ac" "--gc-sections" "-pie" "-zrelro" "-znow"
  = note: rust-lld: error: upxtreme.f7483b69-cgu.8:(.bootblock.boot+0x3039): has non-ABS relocation R_X86_64_PLT32 against symbol '_start'
```

### CODE REVIEW

**Comment by orangecms** [comment]
Another note: We are gettings warnings related to our custom target, `src/custom_targets/x86_64-unknown-none.json`:
```
warning: target json file contains unused fields: eliminate-frame-pointer, no-compiler-rt
```
There are a bunch of settings in there. I'm checking if that is the cause of the issue.

**Comment by orangecms** [comment]
Looking at https://www.spinics.net/lists/linux-efi/msg19404.html, I tried removing the discards - which grows the number of errors.
Adding them all makes the linker dump core. Whoops. :grimacing:

**Comment by orangecms** [comment]
Addendum:
With `relocation-model=pic`, it still yields `rust-lld: error: no memory region specified for section '.got'`

**Comment by orangecms** [comment]
I've narrowed down the breakage to 2021-11-01 (2021-10-31 builds fine). 2021-11-01 was also a release:
https://github.com/rust-lang/rust/releases/tag/1.56.1

**Comment by orangecms** [comment]
So.... walk through this:
https://github.com/rust-lang/rust/commits/ff0e14829

@whentze hinted me towards https://github.com/rust-lang/cargo-bisect-rustc

could take a while... :grimacing:

**Comment by orangecms** [comment]
The good news:
https://github.com/rust-lang/rust/compare/ff0e14829..e249ce6b2
says only

>  106 change files with 137 additions and 650 deletions

**Comment by orangecms** [comment]
Suspicion: https://github.com/rust-lang/rust/pull/89062 introduced `x86_64-unknown-none` as an actual target. Prior to that, we had defined it as a custom target only.

**Comment by orangecms** [comment]
Indeed: It now defaults to `rust-lld`. When I explicitly set the linker to `x86_64-linux-gnu-ld`, it succeeds, though won't fit eventually (why, what was the linker before?)

**Comment by orangecms** [comment]
Adding Rust flag `"linker-flavor=gcc"` to `.cargo/config.toml` has the same effect. I wonder why it's not taken from our custom target.

**Comment by orangecms** [comment]
While some boards succeed to build using gcc for linking (e.g., A300), others are having trouble fitting the sections. :sob: 

upxtreme:
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/upxtreme-15b11700e2d4905e.upxtreme.e213c950-cgu.7.rcgu.o" "-Wl,--as-needed" "-L" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps" "-L" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/release/deps" "-L" "/home/dama/.rustup/toolchains/nightly-2021-11-01-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-none/lib" "-Wl,-Bstatic" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/libcompiler_builtins-741475359bed64b0.rlib" "-Wl,-Bdynamic" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/dama/.rustup/toolchains/nightly-2021-11-01-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-none/lib" "-o" "/home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/upxtreme-15b11700e2d4905e" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-Tlink.ld" "-nostdlib" "-nostartfiles"
  = note: /usr/bin/ld: /home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/upxtreme-15b11700e2d4905e section `.interp' will not fit in region `fspblob'
          /usr/bin/ld: /home/dama/firmware/oreboot/src/mainboard/aaeon/upxtreme/target/x86_64-unknown-none/release/deps/upxtreme-15b11700e2d4905e section `.rela.dyn' will not fit in region `bootblock'
          /usr/bin/ld: section .interp LMA [00000000fffd0000,00000000fffd001b] overlaps section .bootblock LMA [00000000fffd0000,00000000fffff387]
          /usr/bin/ld: region `fspblob' overflowed by 92 bytes
          /usr/bin/ld: region `bootblock' overflowed by 11496 bytes
          collect2: error: ld returned 1 exit status
```
qemu-q35:
```
   Compiling layoutflash v0.1.0 (/home/dama/firmware/oreboot/tools/layoutflash)
WARN rustc_metadata::locator no metadata found: incompatible metadata version found: '/home/dama/firmware/oreboot/tools/layoutflash/target/debug/deps/libclap_derive-b493c6f14ce9d090.so'
WARN rustc_metadata::locator no metadata found: incompatible metadata version found: '/home/dama/firmware/oreboot/tools/layoutflash/target/debug/deps/libnum_derive-83ab074741fb5eb3.so'
    Finished dev [unoptimized + debuginfo] target(s) in 11.15s
     Running `/home/dama/firmware/oreboot/tools/layoutflash/target/x86_64-unknown-linux-gnu/debug/layoutflash target/x86_64-unknown-none/release/fixed-dtfs.dtb target/x86_64-unknown-none/release/image.bin`
<RamPayload DTFS A> @ 0xc00000
<RamPayload DTFS B> @ 0xd00000
<NVRAM B> @ 0xfd8000
<NVRAM A> @ 0xfe8000
<Fixed DTFS> @ 0xff0000
<Boot Blob> @ 0x1000000
failed: File target/x86_64-unknown-none/release/bootblob.bin is too big to fit into the flash area, file size: 67312, area size: 65536
make: *** [../../../../Makefile.mainboard.inc:16: target/x86_64-unknown-none/release/image.bin] Error 1
```

**Comment by orangecms** [comment]
So, objdump comparison:
```
-rwxrwxr-x 1 dama dama 139032 Feb  8 19:58 qemu-35-okay*
-rw-rw-r-- 1 dama dama 903010 Feb  8 20:00 qemu-35-okay.odump
-rwxrwxr-x 1 dama dama 141016 Feb  8 19:57 qemu-35-toobig*
-rw-rw-r-- 1 dama dama 884826 Feb  8 20:00 qemu-35-toobig.odump
```

okay:
```
00000000ffff31a8 <_ZN4arch7bzimage7BzImage4load17h4e0f830e5226b131E>:
_ZN4arch7bzimage7BzImage4load17h4e0f830e5226b131E():
    ffff31a8:   55                      push   %rbp
    ffff31a9:   41 57                   push   %r15
    ffff31ab:   41 56                   push   %r14
    ffff31ad:   41 55                   push   %r13
    ffff31af:   41 54                   push   %r12
    ffff31b1:   53                      push   %rbx
    ffff31b2:   48 81 ec 18 16 00 00    sub    $0x1618,%rsp
    ffff31b9:   49 89 d6                mov    %rdx,%r14
    ffff31bc:   48 89 7c 24 08          mov    %rdi,0x8(%rsp)
    ffff31c1:   4c 8b 7e 18             mov    0x18(%rsi),%r15
    ffff31c5:   48 89 74 24 10          mov    %rsi,0x10(%rsp)
    ffff31ca:   4c 8b 66 20             mov    0x20(%rsi),%r12
    ffff31ce:   48 8d bc 24 48 02 00 00         lea    0x248(%rsp),%rdi
    ffff31d6:   6a 7b                   push   $0x7b
    ffff31d8:   5b                      pop    %rbx
    ffff31d9:   31 f6                   xor    %esi,%esi
    ffff31db:   48 89 da                mov    %rbx,%rdx
    ffff31de:   e8 91 27 00 00          call   ffff5974 <memset>
    ffff31e3:   49 81 fc f1 01 00 00    cmp    $0x1f1,%r12
    ffff31ea:   0f 86 37 06 00 00       jbe    ffff3827 <_ZN4arch7bzimage7BzImage4load17h4e0f830e5226b131E+0x67f>
    ffff31f0:   49 8d 94 24 0f fe ff ff         lea    -0x1f1(%r12),%rdx
```
toobig:
```
00000000ffff31a8 <_ZN4arch7bzimage7BzImage4load17h4e0f830e5226b131E>:
_ZN4arch7bzimage7BzImage4load17h4e0f830e5226b131E():
    ffff31a8:   55                      push   %rbp
    ffff31a9:   41 57                   push   %r15
    ffff31ab:   41 56                   push   %r14
    ffff31ad:   41 55                   push   %r13
    ffff31af:   41 54                   push   %r12
    ffff31b1:   53                      push   %rbx
    ffff31b2:   48 81 ec 18 16 00 00    sub    $0x1618,%rsp
    ffff31b9:   49 89 d6                mov    %rdx,%r14
    ffff31bc:   48 89 7c 24 08          mov    %rdi,0x8(%rsp)
    ffff31c1:   4c 8b 7e 18             mov    0x18(%rsi),%r15
    ffff31c5:   48 89 74 24 10          mov    %rsi,0x10(%rsp)
    ffff31ca:   4c 8b 66 20             mov    0x20(%rsi),%r12
    ffff31ce:   48 8d bc 24 48 02 00 00         lea    0x248(%rsp),%rdi
    ffff31d6:   6a 7b                   push   $0x7b
    ffff31d8:   5b                      pop    %rbx
    ffff31d9:   31 f6                   xor    %esi,%esi
    ffff31db:   48 89 da                mov    %rbx,%rdx
    ffff31de:   e8 91 27 00 00          call   ffff5974 <memset>
    ffff31e3:   49 81 fc f1 01 00 00    cmp    $0x1f1,%r12
    ffff31ea:   0f 86 37 06 00 00       jbe    ffff3827 <_ZN4arch7bzimage7BzImage4load17h4e0f830e5226b131E+0x67f>
    ffff31f0:   49 8d 94 24 0f fe ff ff         lea    -0x1f1(%r12),%rdx
    ffff31f8:   48 83 fa 7b             cmp    $0x7b,%rdx
    ffff31fc:   48 0f 43 d3             cmovae %rbx,%rdx
    ffff3200:   49 8d b7 f1 01 00 00    lea    0x1f1(%r15),%rsi
    ffff3207:   4c 8d ac 24 48 02 00 00         lea    0x248(%rsp),%r13
```
Turns out stack probing can not yet be linined (even in rust master):
https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/x86_64_unknown_none.rs#L16

Is that the only issue though?

**Comment by orangecms** [comment]
Things still to try:

- bump binutils in `Makefile`
- try `"stack-probes": { "kind": "none" },` in custom target and in Cargo configs

**Comment by orangecms** [comment]
Regarding the `stack-probes` setting and PIE/PIC, see also:
https://users.rust-lang.org/t/possible-bug-in-rustc-with-x86-64-unknown-none-target/69674/4

**Review by rminnich — APPROVED** [review]

**Pull request merged**
