### PR TITLE
WIP: Update QEMU to 4.2-rc0

### PR DESCRIPTION
**Pull request by alistair23**
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

### CODE REVIEW

**Comment by alistair23** [comment]
Don't merge! I'm trying to test. My local setup isn't work for some reason

**Comment by alistair23** [comment]
I am seeing errors like this on my machine:
```
rust-lld: error: undefined symbol: __atomic_store_16
```
so I can't test locally.

**Comment by rminnich** [comment]
diff --git a/src/soc/sifive/fu540/src/init.S b/src/soc/sifive/fu540/src/init.S
index f3f510c964..fa0c02112f 100644
--- a/src/soc/sifive/fu540/src/init.S
+++ b/src/soc/sifive/fu540/src/init.S
@@ -1,4 +1,9 @@
-
+.globl __atomic_store_16
+__atomic_store_16:
+       ret
+.globl __atomic_load_16
+__atomic_load_16:
+       ret
 .globl _stack_ptr
 .section .rodata
 _stack_ptr: .word 0x08010000

fixes it.

can riscv do 16-bit aligned atomic load and store? If not, could that be the issue?

**Comment by alistair23** [comment]
Can you re-paste the diff as a code segment? I can't understand what you are changing.

It only has atomic load/store word and double, so no 16-bit.

**Comment by rminnich** [comment]
annoying github.

`+.globl __atomic_store_16
+__atomic_store_16:
+       ret
+.globl __atomic_load_16
+__atomic_load_16:
+       ret
 .globl _stack_ptr
 .section .rodata
 _stack_ptr: .word 0x08010000`

**Comment by rminnich** [comment]
alistair, does this work for you too?

**Comment by alistair23** [comment]
Yep, that fix works for me. I'm going to close this PR and open a correct one.

**Pull request closed without merging**
