### PR TITLE
Update to embedded-hal 1.0 throughout the project

### PR DESCRIPTION
**Pull request by felipebalbi**

### CODE REVIEW

**Comment by felipebalbi** [comment]
Fails due to missing #728

**Review by orangecms — APPROVED** [review]
Nice, thank you!

this tarpaulin thing ... let's kick it out, serves no value at this point.

**Comment by felipebalbi** [comment]
@orangecms even after removing `tarpaulin`, we still need to Bump rust version because of some `clap` dependency:

```
Caused by:
  package `clap_complete v4.5.1` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0
```

We still need to merge #728 before any of the other PRs will work.

**Comment by felipebalbi** [comment]
Yeah, anything under the `clap` umbrella has MSRV listed to rust 1.74, see https://github.com/clap-rs/clap/blob/f65d421607ba16c3175ffe76a20820f123b6c4cb/Cargo.toml#L17

**Review by orangecms — APPROVED** [review]

**Comment by orangecms** [comment]
Gotcha, thank you so much for clearing all of this out!

**Pull request merged**
