### PR TITLE
a300 picasso acpi debug

### PR DESCRIPTION
**Pull request by orangecms**
- asrock/a300m-stx: Remove extraneous MSR APIC configuration
- soc/amd/smn: format numbers with underscores
- asrock/a300m-stx: Exceptions WIP
- go boom
- timer
- debug print crap
- Revert "debug print crap"
- wip
- soc/picasso: df topology
- soc/picasso: topology
- asrock/a300m-stx: disable legacy UART decode
- asrock/a300m-stx: switch to port 0x80 debug output
- Revert "asrock/a300m-stx: switch to port 0x80 debug output"
- asrock/a300m-stx: make code readable
- asrock/a300m-stx: make main readable
- asrock/a300m-stx: SMN hack setup
- asrock/a300m-stx: SMN WIP
- asrock/a300m-stx: comment out SMN hack again
- asrock/a300m-stx: put the stack somewhere else than GDT
- asrock/a300m-stx: use EAX instead of ESP for writing PML4 to CR3
- asrock/a300m-stx: move stack again
- asrock/a300m-stx: print welcome once, not 32 times
- asrock/a300m-stx: ACPI table debug
- asrock/a300m-stx: ACPI table debug
- asrock/a300m-stx: comment out some ACPI
- asrock/a300m-stx: [WIP] watchdog notes
- asrock/a300m-stx: [WIP] watchdog fun
- asrock/a300m-stx: switch to using amd/common/boot
- asrock/a300m-stx: remove redundant and unused code
- AMD: Update x86_64 dependency to 0.14.0.
- asrock/a300m-stx: downgrade x86_64 to 0.13.x
- TEMP HACK: strip down common APCI setup
- asrock/a300m-stx: comment out acpi_setup

### CODE REVIEW

**Comment by felixsinger** [comment]
I think we can close this, since we are removing x86 support?

**Comment by orangecms** [comment]
> I think we can close this, since we are removing x86 support?

Wasn't the point to removed blob based ports? This is source-only.

**Comment by felixsinger** [comment]
My understanding was that we drop x86 support in general, but I might be wrong.

**Comment by ArthurHeymans** [comment]
> My understanding was that we drop x86 support in general, but I might be wrong.

Maybe that statement was accidentally too broad but intended at not supporting necessary executable blobs like FSP?

**Pull request closed without merging**
