### PR TITLE
fix halt. Add tool to create rust from .json. add opentitan uart.

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by rminnich** [comment]
this builds for me, what's up with out test?

**Comment by rjoleary** [comment]
> this builds for me, what's up with out test?

The test seem to pass?

**Comment by alistair23** [comment]
I haven't had a chance to look through this in detail, but a tool to generate rust code from the OT json would be awesome. I was thinking on adding the same thing for Tock, hopefully instead we can just extend this one to work for both.

**Comment by gkelly** [comment]
Our hjson format isn't fixed, it gets new features not-infrequently.  It would probably make sense to add rust generation to the opentitan tooling and consume that output instead of having an out-of-tree parser.

**Comment by alistair23** [comment]
That is a good idea. Auto generating the Tock register interface would be super useful.

**Pull request merged**
