### PR TITLE
Fix compilation issues with qemu-armv7.

### PR DESCRIPTION
**Pull request by niting**
This fixes the compilation issues with qemu-armv7 version but there is still a linker error related to the nostd usage. Plan is to fix the linker error in subsequent changes.

Linker error that remains is: 

note: rust-lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
          rust-lld: error: undefined hidden symbol: __aeabi_uldivmod

#250 is the associated issue.

### CODE REVIEW

**Comment by fotonick** [comment]
@niting, thanks for the contribution. I'd propose blocking this on issue #259, which is for the `rust-lld` error. I'd feel much happier with CI being green.

**Comment by niting** [comment]
Thanks Nickolas - that makes perfect sense! I kind of thought that this was not my commit but due to upstream toolchain changes but wasn't sure.

**Comment by fotonick** [comment]
Ok, CI pipeline is green. Please:
1. Rebase
2. Update the Makefile at the root of the project to unblacklist and rewhitelist qemu-armv7. (It's a bit of a mess.)
3. Push and see that the CI builds.

Sorry for the extra hoops!

**Comment by niting** [comment]
Thank you Nickolas and Ron! I confirmed locally that the build succeeds now. I also noticed #261 whitelisted the build.

**Pull request merged**
