### PR TITLE
add code coverage to azure devops

### PR DESCRIPTION
**Pull request by gogo2464**

### CODE REVIEW

**Review by rminnich — CHANGES_REQUESTED** [review]
we stopped using azure, sorry, our fault! we should have removed it. 
Can you move this to the github actions?

**Comment by gogo2464** [comment]
I just have registered to azure devops but ok :/. Do you want that I registered to travis ci cd too?

**Comment by gogo2464** [comment]
I have finished to set up the yml file and to edit the secret. To make it work I need now to edit the Makefile.

**Comment by gogo2464** [comment]
I have an issue with the permission. Please merge https://github.com/oreboot/oreboot/pull/537 instead.

**Pull request closed without merging**
