### PR TITLE
Fix azure pipelines patch to qemu by checking out known-good ref of qemu

### PR DESCRIPTION
**Pull request by rminnich**
The messages are a bit more verbose but it is still better than
things like

error 2

which we got before

### CODE REVIEW

**Comment by rminnich** [comment]
what on earth? hub is weird sometimes. This is the "checkout a known good ref" PR

**Comment by rminnich** [comment]
I'm wondering if we shouldn't sneak this one in ahead of alistair's patch as it simple. Not sure.

**Comment by alistair23** [comment]
I don't think this is a good idea, we should just update the patch for the latest QEMU.

**Comment by rjoleary** [comment]
Approved to unblock PRs in the short-term. In the long-term, we should update the diff (or upstream parts of it).

**Comment by rminnich** [comment]
I want that ref in there however. can you now update your PR to include the checkout of the proper ref? qemu is a moving target, so if you want to apply a patch to it, you need to pick the ref that patch works for. Else we get to where we are now where a lot of new PRs break for no reason.

**Comment by rminnich** [comment]
alistair has a good PR for updating qemu. 

But we should always use a ref the patch will work against.

**Pull request merged**
